apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finmind.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finmind.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  PORT: {{ .Values.backend.port | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
