apiVersion: v1
kind: Service
metadata:
  name: {{ include "finmind.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "finmind.selectorLabels" . | nindent 4 }}
